### ISSUE TITLE
pnx核心启动时插件报错

### ISSUE THREAD

**Issue by Mitpoppy** [BlocklyNukkit/TechDawn#3]
```
核心：powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded
客户端版本：1.18.10
java：18
```
按教程在使用科技黎明插件时报错，全部插件匀为最新版本
报错：
`16:37:54 [WARN ] [BlocklyNukkit]: 加载BN插件包: TechDawn.bnpx
16:37:55 [ERROR] [BlocklyNukkit]: 无法加载： TechDawn.bnpx
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @28f3a218
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:200) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:194) ~[?:?]
        at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159) ~[BlocklyNukkit.jar:?]
        at javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213) ~[BlocklyNukkit.jar:?]
        at javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52) ~[BlocklyNukkit.jar:?]
        at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260) ~[BlocklyNukkit.jar:?]
        at javassist.ClassPool.toClass(ClassPool.java:1240) ~[BlocklyNukkit.jar:?]
        at javassist.ClassPool.toClass(ClassPool.java:1098) ~[BlocklyNukkit.jar:?]
        at javassist.ClassPool.toClass(ClassPool.java:1056) ~[BlocklyNukkit.jar:?]
        at javassist.CtClass.toClass(CtClass.java:1298) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.JavaExporter.processMethod(JavaExporter.java:70) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.JavaExporter.makeExportJava(JavaExporter.java:32) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.JavaScriptLoader.formatExportJavaScript(JavaScriptLoader.java:194) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.JavaScriptLoader.putJavaScriptEngine(JavaScriptLoader.java:90) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.JavaScriptLoader.putEngine(JavaScriptLoader.java:86) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.BNPackageLoader.runPlugins(BNPackageLoader.java:144) ~[BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.scriptloader.BNPackageLoader.loadplugins(BNPackageLoader.java:56) [BlocklyNukkit.jar:?]
        at com.blocklynukkit.loader.Loader.onEnable(Loader.java:252) [BlocklyNukkit.jar:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:461) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:958) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:947) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?
        at cn.nukkit.Server.<init>(Server.java:785) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:200) [powernukkitx-1.6.0.0-PNX-SNAPSHOT-shaded.jar:?]`

**Comment by Mitpoppy** [comment]
bn不适配java17更换beta版本bn已解决
